### ISSUE TITLE
Incluir Flyway no exemplo

### ISSUE THREAD

**Issue by brunosales** [dclick/modelo-java#2]

**Comment by julianopontes** [comment]
O Flyway só precisa ser adicionada como dependência e configurar os scripts de inicialização que o spring-boot ja roda ele automaticamente.

**Comment by brunosales** [comment]
Verdade @julianopontes, precisa fazer um teste default pra validar que ele ta rodando no projeto também

**Comment by lucasgmartins** [comment]
@julianopontes precisa configurar pra ele rodar os scritps somente em prod, separei em profiles, mas estou com um problema que nos tests ele ignora o application.properties e tenta inicializar o flyway.

**Comment by brunosales** [comment]
@lucasgmartins, a gente roda os scripts do Holmes em QA também. Mesma coisa no Sonyguru. Eu acho que tem que rodar em todo lugar isso.
Outra coisa é evitar o máximo o uso de profile, pra termos sempre o mesmo projeto rodando em dev, qa, prod, etc...

**Comment by julianopontes** [comment]
@brunosales Você viu algo do docker com banco oracle? Temos vários projetos que são Oracle.
