### ISSUE TITLE
Trocando a API de form para JSON

### ISSUE THREAD

**Issue by brunosales** [dclick/modelo-java#22]
JSON é o padrão correto da api rest, e quando subi o que tinha feito fiz com www-form, mudei o formato pra json.

**Comment by brunosales** [comment]
@brunoqueiroz, falei com o fachine e o padrão é sempre ter API via JSON, está certo?
@julianopontes, @lucasgmartins, @facholi , @marcelofelix, @mvfernandes88, @ericdulcetti Fiz as mudanças para json, deem uma olhada e se tiver ok de merge pra master.

@ericdulcetti, acho que é interessante você pegar essa mudança pro projeto do sesc. Qualquer coisa fala comigo.

**Comment by brunoqueiroz** [comment]
sim @brunosales.
