### ISSUE TITLE
Problema no Test ApplicationAuthenticationTest em java 7

### ISSUE THREAD

**Issue by brunoqueiroz** [dclick/modelo-java#34]
Classe não compila no java 7, problema para alguns projetos que ainda precisam de java 7. 
Qualquer coisa falar com o Igor.

**Comment by brunosales** [comment]
Bruno, essas coisas não deveriam ir para o modelo, temos que ter o modelo atualizar sempre com tudo que for melhor e mais moderno, caso seja necessário uma implementação específica para algum cliente, abre um branch e coloca lá

**Comment by brunoqueiroz** [comment]
Concordo com você Sales, é mais pra deixar no radar, tem uma branch (ou deveria ter) para o pessoal que ainda precisa utilizar o java 7. Acredito que já existe então é mais para ajusta na branch do "java7"

**Comment by ericdulcetti** [comment]
A branch "sesc-auth" está com java 7.

**Comment by brunoqueiroz** [comment]
Vi aqui na branch @eric você já tinha ajustado o import o problema não existe mais na sesc-auth.
https://github.com/dclick/modelo-java/blob/9a2c7ab537e1e2f982e88e2886f46a4e6520487c/server/src/test/java/io/redspark/security/ApplicationAuthenticationTest.java#L14

Valeu!
